
name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  my_first_job:
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo Agregando mi primer job,
          echo despues se pueden agregar otros
